[iOS] Update the Sample App for iOS
microsoft/quick-authentication pull request #15
Opened 2022-10-13 08:34 UTC by minggangw

This patch does:

1. Updates the MSQASignIn framework that includes the recent changes, which are:

   - Support the telemetry functionality.
   - Support the logging functionality.
   - Support the given name/surname/email for MSA account.

3. Updates the Sample app accordingly per the changes above.

2022-10-13 09:10 UTC, minggangw commented
Only the file, `demos/iOS/SampleAppiOS/SampleMainViewController.m`, gets updated for the sample app itself, for other changes are introduced from the binary framework located at `demos/iOS/MSQASignIn.framework/`

2022-10-14 02:14 UTC, chbhatt requested changes

2022-10-14 02:14 UTC, chbhatt commented on demos/iOS/MSQASignIn.framework/PrivateHeaders/MSQALogger.h
> +//------------------------------------------------------------------------------
Shouldn't MSQALogger.h be public header?

2022-10-14 02:14 UTC, chbhatt commented on demos/iOS/MSQASignIn.framework/PrivateHeaders/MSQAAccountData_Private.h
> +- (void)setBase64Photo:(NSString *)base64Photo;
Do we need to put the PrivateHeaders into framework?

2022-10-17 05:59 UTC, minggangw commented on demos/iOS/MSQASignIn.framework/PrivateHeaders/MSQALogger.h
> +//------------------------------------------------------------------------------
has moved to public

2022-10-17 06:07 UTC, minggangw commented on demos/iOS/MSQASignIn.framework/PrivateHeaders/MSQAAccountData_Private.h
> +- (void)setBase64Photo:(NSString *)base64Photo;
Has moved all "xxx_Private.h" headers out of the framework

2022-11-03 21:54 UTC, chbhatt approved these changes

2022-11-04 03:29 UTC, merged